apiVersion: v1
kind: Service
metadata:
  name: venuefinderrelease2-mongodb-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: venuefinderrelease2
    app.kubernetes.io/name: mongodb
